/*
 * InterfaceServeurAboutBox.java
 */

package interfaceserveur;

import javax.swing.DefaultListModel;
import org.jdesktop.application.Action;

public class InterfaceEmployer extends javax.swing.JDialog {

    private DefaultListModel ListedesEmployes;

    public InterfaceEmployer(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(boutonAjouterEmploye);
    }



    @Action public void fermerFenetre() {
        dispose();
    }

    @Action public void supprimerEmploye() {
        //ListedesEmployes.addElement("Monday");
       // ListedesEmployes.addElement("Tuesday");
       // ListedesEmployes.addElement("Wednesday");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel imageLabel = new javax.swing.JLabel();
        PanneauListeEmployes = new javax.swing.JScrollPane();
        listeEmployes = new javax.swing.JList();
        champLogin = new javax.swing.JTextField();
        champTerminalAssigne = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        labelMotdePasse = new javax.swing.JLabel();
        labelTerminalAssigne = new javax.swing.JLabel();
        javax.swing.JLabel labelDescriptionMission = new javax.swing.JLabel();
        boutonAssignerMission = new javax.swing.JButton();
        labelListeMissionsAssignees = new javax.swing.JLabel();
        boutonSupprimerEmploye = new javax.swing.JButton();
        boutonAjouterEmploye = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(interfaceserveur.InterfaceServeurApp.class).getContext().getResourceMap(InterfaceEmployer.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        imageLabel.setIcon(resourceMap.getIcon("imageLabel.icon")); // NOI18N
        imageLabel.setName("imageLabel"); // NOI18N

        PanneauListeEmployes.setName("PanneauListeEmployes"); // NOI18N

        listeEmployes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Robert (5)", "Norbert (2)", "Jeanne d'Arc (1)", "Jean Balistique (?)", "Michel Colluchi (0)" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listeEmployes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listeEmployes.setName("listeEmployes"); // NOI18N
        PanneauListeEmployes.setViewportView(listeEmployes);

        champLogin.setText(resourceMap.getString("champLogin.text")); // NOI18N
        champLogin.setName("champLogin"); // NOI18N

        champTerminalAssigne.setText(resourceMap.getString("champTerminalAssigne.text")); // NOI18N
        champTerminalAssigne.setName("champTerminalAssigne"); // NOI18N

        labelLogin.setText(resourceMap.getString("labelLogin.text")); // NOI18N
        labelLogin.setName("labelLogin"); // NOI18N

        labelMotdePasse.setText(resourceMap.getString("labelMotdePasse.text")); // NOI18N
        labelMotdePasse.setName("labelMotdePasse"); // NOI18N

        labelTerminalAssigne.setText(resourceMap.getString("labelTerminalAssigne.text")); // NOI18N
        labelTerminalAssigne.setName("labelTerminalAssigne"); // NOI18N

        labelDescriptionMission.setFont(labelDescriptionMission.getFont().deriveFont(labelDescriptionMission.getFont().getStyle() | java.awt.Font.BOLD, labelDescriptionMission.getFont().getSize()+4));
        labelDescriptionMission.setText(resourceMap.getString("labelDescriptionMission.text")); // NOI18N
        labelDescriptionMission.setName("labelDescriptionMission"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(interfaceserveur.InterfaceServeurApp.class).getContext().getActionMap(InterfaceEmployer.class, this);
        boutonAssignerMission.setAction(actionMap.get("fermerFenetre")); // NOI18N
        boutonAssignerMission.setText(resourceMap.getString("boutonAssignerMission.text")); // NOI18N
        boutonAssignerMission.setName("boutonAssignerMission"); // NOI18N

        labelListeMissionsAssignees.setText(resourceMap.getString("labelListeMissionsAssignees.text")); // NOI18N
        labelListeMissionsAssignees.setName("labelListeMissionsAssignees"); // NOI18N

        boutonSupprimerEmploye.setText(resourceMap.getString("boutonSupprimerEmploye.text")); // NOI18N
        boutonSupprimerEmploye.setName("boutonSupprimerEmploye"); // NOI18N

        boutonAjouterEmploye.setText(resourceMap.getString("boutonAjouterEmploye.text")); // NOI18N
        boutonAjouterEmploye.setName("boutonAjouterEmploye"); // NOI18N

        jPasswordField1.setText(resourceMap.getString("jPasswordField1.text")); // NOI18N
        jPasswordField1.setName("jPasswordField1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelDescriptionMission)
                .addContainerGap(458, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boutonSupprimerEmploye, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(PanneauListeEmployes, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(boutonAssignerMission, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelListeMissionsAssignees)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelTerminalAssigne)
                                            .addComponent(labelMotdePasse)
                                            .addComponent(labelLogin))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(champLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(champTerminalAssigne, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boutonAjouterEmploye)))))))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDescriptionMission)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(champLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelLogin))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelMotdePasse)
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(champTerminalAssigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelTerminalAssigne))
                                .addGap(18, 18, 18)
                                .addComponent(boutonAjouterEmploye))
                            .addComponent(imageLabel))
                        .addGap(34, 34, 34)
                        .addComponent(labelListeMissionsAssignees)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addComponent(boutonAssignerMission, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PanneauListeEmployes, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boutonSupprimerEmploye)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane PanneauListeEmployes;
    private javax.swing.JButton boutonAjouterEmploye;
    private javax.swing.JButton boutonAssignerMission;
    private javax.swing.JButton boutonSupprimerEmploye;
    private javax.swing.JTextField champLogin;
    private javax.swing.JTextField champTerminalAssigne;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel labelListeMissionsAssignees;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelMotdePasse;
    private javax.swing.JLabel labelTerminalAssigne;
    private javax.swing.JList listeEmployes;
    // End of variables declaration//GEN-END:variables
    
}
